name: Create PR with dependencies to main
on: workflow_dispatch

jobs:
  run_checks:
    name: Create pull request to main branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dependencies branch
        uses: actions/checkout@v2
        with:
          ref: dependencies-update
          fetch-depth: 0
      - name: Set user name and email for Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Update dependencies branch from main
        run: git merge origin/main
      - name: Push updated dependencies branch
        run: git push
      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: dependencies-update
          destination_branch: main
          pr_title: 'Update dependencies in batch'
          pr_label: dependencies
          github_token: ${{ secrets.GITHUB_TOKEN }}
